#ifndef _WEAPONS_CONSTS_H_
#define _WEAPONS_CONSTS_H_

#include <types.h>
#include <consts.h>

#define WEAPON_BASE_PAL PAL2
#define WEAPON_USED_PALS 1

#define WEAPON_SPRITE_X_CENTERED (TILEMAP_COLUMNS/2)*8
#define WEAPON_SPRITE_Y_ABOVE_HUD (VERTICAL_ROWS)*8 - 0 // -1 scanline: used for hint DMA hud palettes when the VDP is turned off
#define WEAPON_SPRITE_FIST_X (WEAPON_SPRITE_X_CENTERED - ((WEAPON_FIST_ANIM_WIDTH+1)/2)*8 - 3*8)
#define WEAPON_SPRITE_FIST_Y (WEAPON_SPRITE_Y_ABOVE_HUD - WEAPON_FIST_ANIM_HEIGHT*8)
#define WEAPON_SPRITE_PISTOL_X (WEAPON_SPRITE_X_CENTERED - ((WEAPON_PISTOL_ANIM_WIDTH+1)/2)*8 - 8)
#define WEAPON_SPRITE_PISTOL_Y (WEAPON_SPRITE_Y_ABOVE_HUD - WEAPON_PISTOL_ANIM_HEIGHT*8)
#define WEAPON_SPRITE_SHOTGUN_X (WEAPON_SPRITE_X_CENTERED - ((WEAPON_SHOTGUN_ANIM_WIDTH+1)/2)*8 - 2*8)
#define WEAPON_SPRITE_SHOTGUN_Y (WEAPON_SPRITE_Y_ABOVE_HUD - WEAPON_SHOTGUN_ANIM_HEIGHT*8)

#define WEAPON_FIST_ANIM_WIDTH 20
#define WEAPON_FIST_ANIM_HEIGHT 10
#define WEAPON_PISTOL_ANIM_WIDTH 11
#define WEAPON_PISTOL_ANIM_HEIGHT 13
#define WEAPON_SHOTGUN_ANIM_WIDTH 15
#define WEAPON_SHOTGUN_ANIM_HEIGHT 17

#define WEAPON_START_HIT_FRAME 1 // All sprites fire animations start at the same frame
#define WEAPON_FIST_ANIM_READY_TO_HIT_AGAIN_FRAME 1
#define WEAPON_PISTOL_ANIM_READY_TO_HIT_AGAIN_FRAME 3
#define WEAPON_SHOTGUN_ANIM_READY_TO_HIT_AGAIN_FRAME 0

#define WEAPON_CHANGE_COOLDOWN_TIMER 8 // This has to be bigger than the effect of scrolling down current weapon and scrolling up new weapon
#define WEAPON_RESET_TO_IDLE_TIMER 2*60 // Always >= than largest animation length multiplied by the frequency of animation frames
#define WEAPON_FIST_FIRE_COOLDOWN_TIMER 28
#define WEAPON_PISTOL_FIRE_COOLDOWN_TIMER 24
#define WEAPON_SHOTGUN_FIRE_COOLDOWN_TIMER 42

#define WEAPON_PISTOL_MAX_AMMO 400
#define WEAPON_SHOTGUN_MAX_AMMO 100
#define WEAPON_MACHINE_GUN_MAX_AMMO 400
#define WEAPON_ROCKET_MAX_AMMO 100
#define WEAPON_PLASMA_MAX_AMMO 600
#define WEAPON_BFG_MAX_AMMO 600

#endif // _WEAPONS_CONSTS_H_